### ISSUE TITLE
After Unfreeze the animation should end normally not disappear

### ISSUE THREAD

**Issue by Muhammad-Ashik** [arthurdenner/remotion-lottie-test#11]
I have added <Freeze/> component from remotion to freeze a animation to a certain point. The animation normally appear at 0 sec and ends at 24 secs. The animation appear with a fading effect and ends with fade out. So I want to freeze the animation as long as I want and then if I unfreeze the animation I want it to end with the fade out effect like the normal end.

Currently it's freezing but when I unfreeze it is disappearing. Here is the codesandbox link:
https://codesandbox.io/s/flowcode-animation-forked-fmse9?file=/src/videoPlayer/VideoPlayer.tsx

**Comment by arthurdenner** [comment]
Hi @Muhammad-Ashik! 👋🏽 

The components are behaving as expected. To explain:

- `<Freeze />` provides the same frame to the inner component, so your animation shows the same frame
- Without `<Freeze />`, the animation lasts what's supposed to, 24 seconds
- If you freeze and pass the 24 seconds mark, your animation will have ended, therefore isn't shown

I'm not sure Remotion has a way to control this kind of behaviour (play something, freeze for sometime and then continue), maybe `<Series /> + `<Sequence />`, so I'll ping @JonnyBurger here.

In any case, I'll explore this a bit more later today. I suppose the `<RemotionLottie />` will need a `startFrom` kind of prop.

**Comment by arthurdenner** [comment]
Hi @Muhammad-Ashik! 👋🏽 

The components are behaving as expected. To explain:

- `<Freeze />` provides the same frame to the inner component, so your animation shows the same frame
- Without `<Freeze />`, the animation lasts what's supposed to, 24 seconds
- If you freeze and pass the 24 seconds mark, your animation will have ended, therefore isn't shown

I'm not sure Remotion has a way to control this kind of behaviour - play something, freeze for some time and then continue.
In any case, I'll explore this a bit more later today and ping @JonnyBurger here to check if he has suggestions.

Here is a simplified version of your sandbox: https://codesandbox.io/s/practical-curran-bp46q?file=/src/Composition.tsx

**Comment by Muhammad-Ashik** [comment]
@arthurdenner Thank you for the reply. I know the animation without `<Freeze/>` lasts for 24 seconds. But I want that animation to be freeze in a frame so I can increase the animation time. Suppose I want the animation play for 50 seconds. For that I want the animation freeze in a frame where the QR code is visible. I can freeze for 45 sec but I am unable to show the ending because it is disappearing. Is there anyway to do that please?

**Comment by JonnyBurger** [comment]
I think you are looking for something like this:

```tsx
return (
	<AbsoluteFill>
		<Sequence from={0} durationInFrames={24 * 30}>
			<MyContent/>
   		</Sequence>
		<Sequence from={24 * 30} durationInFrames={10 * 30}>
			<Freeze frame={24 * 30}>
				<MyContent />
			</Freeze>
		</Sequence>
		<Sequence from={24 * 30 + 10 * 30}>
			<Sequence from={0 - 24 * 30 - 10 * 30}>
				<MyContent />
			</Sequence>
		</Sequence>
	</AbsoluteFill>
)
```

MyContent would be your Lottie animation. It will play the first 24sec, then freeze for 10sec, then continue. Did not test but I think it should work with this code or some tiny tweak.

**Comment by Muhammad-Ashik** [comment]
> I think you are looking for something like this:
> 
> ```tsx
> return (
> 	<AbsoluteFill>
> 		<Sequence from={0} durationInFrames={24 * 30}>
> 			<MyContent/>
>    		</Sequence>
> 		<Sequence from={24 * 30} durationInFrames={10 * 30}>
> 			<Freeze frame={24 * 30}>
> 				<MyContent />
> 			</Freeze>
> 		</Sequence>
> 		<Sequence from={24 * 30 + 10 * 30}>
> 			<Sequence from={0 - 24 * 30 - 10 * 30}>
> 				<MyContent />
> 			</Sequence>
> 		</Sequence>
> 	</AbsoluteFill>
> )
> ```
> 
> MyContent would be your Lottie animation. It will play the first 24sec, then freeze for 10sec, then continue. Did not test but I think it should work with this code or some tiny tweak.

Yeah it should work let me try it. Thank you for the code :) @JonnyBurger

**Comment by Muhammad-Ashik** [comment]
H! @arthurdenner  & @JonnyBurger. The above code is working. I have a question for @JonnyBurger . Can you please explain the nested sequence? I am talking about this:

```
		<Sequence from={24 * 30 + 10 * 30}>
			<Sequence from={0 - 24 * 30 - 10 * 30}>
				<MyContent />
			</Sequence>
		</Sequence>
```
