### ISSUE TITLE
Programmatically changing the JSON hides the animation in the player

### ISSUE THREAD

**Issue by Muhammad-Ashik** [arthurdenner/remotion-lottie-test#7]
I am changing a text in the json programmatically. So changing the JSON hides the animation in the player. But if I click play on the player the animation show with the updated json. If I comment out animation.destroy() then it is not hiding but also not updating json. Is there anyway I can update the json without any problem? If I use react-lottie-player then all the problem resolved but it is not syncing with remotion.

**Comment by arthurdenner** [comment]
Hi @Muhammad-Ashik! I apologize for not getting back to you earlier.
I'm not having much time to open-source at the moment.
I'll have a look at what you described - do you have a reproducible example?

**Comment by arthurdenner** [comment]
PS: Remind that I'm not a Lottie expert, I'm just exploring its integration with Remotion 😄 

The best way to debug this is with a real reproducible example, but here are my thoughts.

I'm really not sure what's the best way to manipulate Lottie animations. It seems like the library cache some things from the JSON, which is why calling `destroy` on data changes seems to be the correct move.

I was wondering if it's fine to call `delayRender` inside a `useEffect` when `data` changes.
I'm referring to changes like #8. @JonnyBurger may be able to contribute to this.

**Comment by JonnyBurger** [comment]
We'll be happy to look into it if a repro is added!

**Comment by Muhammad-Ashik** [comment]
Hi @arthurdenner and @JonnyBurger ! Happy to see you both. I will add codesandbox link tonight or tomorrow.

**Comment by Muhammad-Ashik** [comment]
Hi @JonnyBurger and @arthurdenner ! I hope you both are doing well. Sorry for the late I was sick. I have come with codesandbox link. Here is the link:
https://codesandbox.io/s/flowcode-animation-7md3t?file=/src/Components/LottieAnimation.tsx

If you go to the link you will find a text input on the left side. Play the video and stop at 2 sec, on the top right corner you will see lottie animation with text (Demo Text) and hand icon inside a white ellipse. Then If you type something on the left text input, I update the JSON with the text typed in the input. In the player you will see the animation immediately hides but playing or seek the video the animation appears with the updated JSON and text. That is the problem.

Now here is something I'd like to tell you:
1. Changing the JSON the animation hides. if I play or seek the video then everything is okay.
2. Sometime I got an error which is object is not extensible. I found the reason if I pass the JSON without deep cloning then lottie modify the json but it is unable to modify JSON that's why get an error.
3. Even if you find a solution for the animation hiding then you will see another problem which is blinking effect. Because the animationData prop changes, which causes destroy() and then loadAnimation() to be called. this probably causes a visual flash or a blinking effect in between when there is no lottie tied to the dom element. I'm not sure how best to solve this.
  a. May use a temporary div and loadAnimation on it before destoyring the old one (kind of like double buffering) but it 
      may complicate the code a bit.
  b. Maybe just defer calling destroy on the old one until the new one has finished loadAnimation, although it may cause 
      other issues

**Comment by JonnyBurger** [comment]
Thanks a lot @Muhammad-Ashik! I added this to my todo list to look into it. Will get back to you on this!

**Comment by JonnyBurger** [comment]
Thanks @Muhammad-Ashik! Appreciate the precise description!

From what I understand, the animation should hide when the text is changing?
I opened the Codesandbox and I cannot reproduce it from there somehow. Am I misunderstanding the scenario?

https://user-images.githubusercontent.com/1629785/146640440-5b788f0f-2c1d-432f-8886-dcee4f8e9619.mp4

**Comment by Muhammad-Ashik** [comment]
@JonnyBurger thank you for looking into it. No the animation should not hide if I change text or animationData (JSON). I have found a fix. I have added animationData on line 90 in RemotionLottie.tsx, But still sometime I get the problem. I removed it so you can see the problem. It should work like our useState hook. If I change text it should update the text without any problem.

https://user-images.githubusercontent.com/38232006/146661195-b6e0f59f-9076-432d-942c-1a543ac40971.mp4

**Comment by arthurdenner** [comment]
@Muhammad-Ashik, I apologize for the long wait to get back to you.
I'm only now being able to catch up with open-source. 🙌🏽 

I appreciate your example, it was very useful in debugging!

After some investigation, I realized that destroying the previous animation before loading the new one is fine.
What we were missing was setting the new animation to the same frame as the previous animation was.
So your animation was updated, reloaded but set to its initial state (which is not visible).

I did some changes in #9 and forked your sandbox with the code changes: [link](https://codesandbox.io/s/zi14x?file=/src/Components/RemotionLottie.tsx:1177-1283)
From my tests, the changes are reflected immediately and you can even tweak it while the video is running.

Disclaimer: It's possible that many changes in a short period may result in bugs if something goes wrong (or slow) on the Lottie side.

Note: The deep clone you did shouldn't be part of the `RemotionLottie` component, it should be on the consumer side - e.g. before setting the state.
But to make your example work, I didn't use `lodash.clonedeep`, only a "shallow clone" with `{...animObj}` worked fine 👍🏽

**Comment by Muhammad-Ashik** [comment]
Yes this problem is resolved. Thank you very much @arthurdenner
